# Generated by Django 4.2 on 2025-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0002_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="uuid",
            field=models.CharField(max_length=36),
        ),
    ]
